name= input('Enter your name:')
print('Hello,',name)
num1 = eval(input('Enter The First Number:'))
num2 = eval(input('Ener The Second Number:'))
print(name,',The average of the numbers you entered is',(num1+num2)/2)
